#!/bin/bash

# This script will rename sequences with ">barcodelabel=sample_id;sequence:id", as required by USEARCH otu clustering methods.
# For this script to run correctly input fasta label must be formatted ">sequence_id", and filename must be "sample_id.fasta".
# THIS ONLY WORKS FOR .fasta FILES, NOT .fastq FILES.

input_fasta="input"
ouput_labeled_fasta="output"

########################################################################################################
########################################################################################################

mkdir ${ouput_labeled_fasta}
mkdir working1

########################################
# 1 Remove ">" from start of sequence_ID
########################################

for file1 in input/*.fasta
	do
sed -e 's/>/>barcodelabel=;/g' ${file1} > working1/$(basename "$file1" .fasta).txt 
	done

#######################################################################################
# 2 Add sample_ID (should be filename) to produce ">barcodelabel=sample_ID;sequence_ID"
#######################################################################################

for file2 in working1/*.txt 
	do
sample_id=$(basename ${file2} .txt)
echo ${sample_id}
sed -e "s/;/${sample_id};/g" ${file2} > output/$(basename "$file2" .txt).fasta
	done
  
rm -r working1

echo Complete
echo Script written by Alexander W. Gofton, 2017
	
