#!/bin/bash



singletons_filtered_dir="singleton_filtered_directory"

OTUs_dir="OTU_directory"


echo ""
echo CREATING DIRECTORIES
echo ""

mkdir ${singletons_filtered_dir}
mkdir ${OTUs_dir}
echo ""


echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
echo OTU CLUSTERING AND CHIMERA DETECTION
echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
echo ""
echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

echo ""
echo CONCATENATING FILES TOGETHER
echo""

	cat ${singleton_filtered_dir}/*.fasta > ${OTUs_dir}/all_samples_QF_no_singletons.fasta

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo DEREPLICATING UNIQUE SEQUENCES
echo""

	usearch8 -derep_fulllength ${OTUs_dir}/all_samples_QF_no_singletons.fasta -fastaout ${OTUs_dir}/derep.fasta -sizeout

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo SORTHING REPLICATE CLUSTERS
echo""

	usearch8 -sortbysize ${OTUs_dir}/derep.fasta -fastaout ${OTUs_dir}/derep_sortbysize.fasta -minsize 2

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo CLUSTERING OTUs
echo""

	usearch8 -cluster_otus ${OTUs_dir}/derep_sortbysize.fasta -otus ${OTUs_dir}/otu_rep_seqs.fasta -uc ${OTUs_dir}/otu_clustering_uc_map.txt

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo DETECTING AND FILTERING CHIMERAS
echo""

	usearch8 -uchime_ref ${OTUs_dir}/otu_rep_seqs.fasta -db drive5/gold.fa -strand plus -nonchimeras ${OTUs_dir}/otu_rep_seqs_chimeras_filtered.fasta

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo NUMBERING OTUs
echo""

	python drive5/fasta_number.py ${OTUs_dir}/otu_rep_seqs_chimeras_filtered.fasta OTU_ > ${OTUs_dir}/final_otus.fasta

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo CREATING UCLUST OTU MAP
echo""

	usearch8 -usearch_global ${OTUs_dir}/all_samples_QF_no_singletons.fasta -db ${OTUs_dir}/final_otus.fasta -strand plus -id 0.97 -uc ${OTUs_dir}/final_otus_uc_map.txt

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo CREATING OTU TABLE
echo""

	python drive5/uc2otutab.py ${OTUs_dir}/final_otus_uc_map.txt > ${OTUs_dir}/otu_table.txt

echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
echo ""
echo DONE
echo ""
echo~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

echo Job complete
echo Script written by Alexander W. Gofton 2016
