#!/bin/bash

# PLEASE FILL IN THE BELOW DIRECTORY LOCATIONS
# Note: input_dir must be a existing folder which contains all of
# your .fastq sequence files that have been merged (paired end sequences), primers and distal bases trimmed,
# and batch renamed in the usearch format (barcodelabel=samplename;sequence_identifier)
# All other directories will be created as needed by the script.
# EACH DIRECTORY VALUE MUST HAVE DOUBLE ("") QUOTATION MARKS AROUND IT AND NO SPACES
##########################################################
input_dir="merged_trimmed"
QF_dir="1_QF_directory"
derep_dir="2_derep_dir"
singleton_filtered_dir="3_singleton_filtered_directory"
final_derep_dir="4_final_derep_dir"
whole_dataset_to_blast="5_whole_dataset_to_blast"
###########################################################

# PLEASE FILL IN THE BELOW VARIABLES. BELOW EACH VARIABLE IS A DESCRIPTION WITH PROPER USAGE.
###########################################################
error_rate="0.01"
# The variable error_rate defines the maximum error rate (as a % of sequence length) that will be retained in the dataset. For example with error_rate=0.01 (1%) 100bp reads can have 1bp expected error, and 300bp reads can have 3bp expected error
maxsize="1"
# the variable max size denotes the maximum replicate cluster size that will be removed from the data. eg maxsize=1 only singletons will be removed, maxsize=2 singletons and duplicates will be removed, ETC.
###########################################################
###########################################################
# START OF SCRIPT, EDITING BELOW THIS LINE MAY CAUSE ERRORS IN YOUR ANALYSIS

	echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	echo ""
	echo @@@@@@@@@@@@@@@@@@@@@@@@@
	echo 1. CREATING DIRECTORIES
	echo @@@@@@@@@@@@@@@@@@@@@@@@@
	echo ""
	echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

mkdir ${QF_dir}
mkdir ${derep_dir}
mkdir ${singleton_filtered_dir}
mkdir ${final_derep_dir}
mkdir ${whole_dataset_to_blast}

	echo ""

	echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	echo ""
	echo @@@@@@@@@@@@@@@@@@@@@
	echo 2. QUALITY CONTROL
	echo @@@@@@@@@@@@@@@@@@@@@
	echo ""
	
for filename in ${input_dir}/*.fastq
do
	echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	echo ""
	echo QUALITY CONTROL
	echo input is: ${filename}
	echo max error_rate is: ${error_rate}
	echo ""
usearch8 -fastq_filter ${filename} -fastaout "${QF_dir}/$(basename "$filename" .fastq).fasta" -fastq_maxee_rate ${error_rate}
	echo ""
	echo DONE
	echo ""
	echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
done

	echo ""	
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo 3. Concatenating all QF sequence files
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo ""
	
cat ${QF_dir}/*.fasta > ${derep_dir}/cat_all.fasta

	echo ""		
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo 4. Finding singleton sequence
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo ""

usearch8 -derep_fulllength ${derep_dir}/cat_all.fasta -fastaout ${derep_dir}/derep_all.fasta -sizeout

usearch8 -sortbysize ${derep_dir}/derep_all.fasta -fastaout ${derep_dir}/derep_all_sorted.fasta -maxsize ${maxsize}

	echo ""		
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo 5. Removing singleton sequences from individual sequence files
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@	
	echo ""
	
grep "^>" ${derep_dir}/derep_all_sorted.fasta > ${derep_dir}/singleton_names1.txt
	
sed -e 's/;size=1;//g' -e 's/>//g' ${derep_dir}/singleton_names1.txt > ${derep_dir}/singleton_names2.txt
	
for filename5 in ${QF_dir}/*.fasta
do
	echo ""
	echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
	echo input is: ${filename5}
	echo ""
usearch8 -fastx_getseqs	${filename5} -labels ${derep_dir}/singleton_names2.txt -notmatched "${singleton_filtered_dir}/$(basename "$filename5" .fasta).fasta"
	echo ""
	echo DONE
	echo ""
	echo ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
done

	echo ""
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo 6. Derep individual sample files for BLAST
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo ""
	
for filename6 in ${singleton_filtered_dir}/*.fasta
do
	echo ""
	echo Dereplicating per sampl e fo r BLAST	
	echo input is: ${filename5}
	echo ""
usearch8 -derep_fulllength ${filename6} -fastaout "${final_derep_dir}/$(basename "$filename6" .fasta).fasta" -sizeout
done 
	
	echo ""
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo 7. Concatenating all QF and SF individual sample files into one .fasta for BLAST
	echo @@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
	echo ""
	
cat ${final_derep_dir}/*.fasta > ${whole_dataset_to_blast}/final_all.fasta

echo Job complete
echo Script written by Alexander W. Gofton 2016
